CREATE TABLE STORAGE (
id NUMBER,
CONSTRAINT STORAGE_PK PRIMARY KEY (id),
formatsSupported VARCHAR(90) ,
storageCountry VARCHAR(20),
storageMaxSize NUMBER
);

CREATE TABLE FI (
id NUMBER,
CONSTRAINT FIL_PK PRIMARY KEY (id),
nameFile VARCHAR(45) UNIQUE,
formatFile VARCHAR(45),
sizeFile NUMBER,
storageId NUMBER,
CONSTRAINT STORAGE_FC FOREIGN KEY (storageId) REFERENCES STORAGE(ID)
)
